[[LLVMLibcxx]]
arch = "x86_64"
git-tree-sha1 = "a2aba14678e1ae583052dad243da081e08166388"
libc = "glibc"
os = "linux"

    [[LLVMLibcxx.download]]
    sha256 = "8c1c259d6782e43d1775c121dd507ca8c0ba2a0a7c95377adf69b63f54a5e36e"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.0/LLVMLibcxx-v17.0.0-x86_64-linux-gnu.tar.gz"
[[LLVMLibcxx]]
arch = "i686"
git-tree-sha1 = "dbbe095635585ce8090da0aac84cb934cc36aa4c"
libc = "glibc"
os = "linux"

    [[LLVMLibcxx.download]]
    sha256 = "ea50dec5ec97deb1087f0f8a196f5c6b5b3a38598bfc0291515c27a183cb854d"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.0/LLVMLibcxx-v17.0.0-i686-linux-gnu.tar.gz"
[[LLVMLibcxx]]
arch = "aarch64"
git-tree-sha1 = "07ee70816a5a695851e91fba86107f936ab56623"
libc = "glibc"
os = "linux"

    [[LLVMLibcxx.download]]
    sha256 = "266726aa9cc96ccb6ad0eb17bf3097bce71921b72bcf3eefb601eed9388d9a06"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.0/LLVMLibcxx-v17.0.0-aarch64-linux-gnu.tar.gz"
[[LLVMLibcxx]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c7d09254e0e929e980c348240f588351c2ae80d7"
libc = "glibc"
os = "linux"

    [[LLVMLibcxx.download]]
    sha256 = "a634fb7814d94e0760f06ed1f8ee08074ffa6c5371f73b8eba6a0181700c19b2"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.0/LLVMLibcxx-v17.0.0-armv7l-linux-gnueabihf.tar.gz"
[[LLVMLibcxx]]
arch = "powerpc64le"
git-tree-sha1 = "5be50b7e9a353b3b06b860d0fb47d418c171e075"
libc = "glibc"
os = "linux"

    [[LLVMLibcxx.download]]
    sha256 = "1d2622123343ea7087be6b1ff71d64251add0e70f8607288b4afa133c65819c6"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.0/LLVMLibcxx-v17.0.0-powerpc64le-linux-gnu.tar.gz"
[[LLVMLibcxx]]
arch = "x86_64"
git-tree-sha1 = "af7c34a709451a96a1976b9c0f0d1dcd60a2ff16"
libc = "musl"
os = "linux"

    [[LLVMLibcxx.download]]
    sha256 = "29738f8514195c912066924199b40c8fd396e3be3c0c32be94033d336e423a23"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.0/LLVMLibcxx-v17.0.0-x86_64-linux-musl.tar.gz"
[[LLVMLibcxx]]
arch = "i686"
git-tree-sha1 = "d69bd2a8f41a287350f046756da2f56324bd37ae"
libc = "musl"
os = "linux"

    [[LLVMLibcxx.download]]
    sha256 = "1079a21d7496c8257bcc68377309dc4ecb90c78f36d8867790923a971528cc15"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.0/LLVMLibcxx-v17.0.0-i686-linux-musl.tar.gz"
[[LLVMLibcxx]]
arch = "aarch64"
git-tree-sha1 = "e7cbacb7fba1337ff99ed98df94ddda01b3e9329"
libc = "musl"
os = "linux"

    [[LLVMLibcxx.download]]
    sha256 = "3cdf2ed70e371129cfbc3bb3251bc2aa8a89413faadc1ff125f7261807e0d1ee"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.0/LLVMLibcxx-v17.0.0-aarch64-linux-musl.tar.gz"
[[LLVMLibcxx]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "33da202d1939f358132f4be8f63c0a42c20a2daa"
libc = "musl"
os = "linux"

    [[LLVMLibcxx.download]]
    sha256 = "55d27712029621c1a2f6db401ec8af9c3317459172d422406a7341738f340c63"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.0/LLVMLibcxx-v17.0.0-armv6l-linux-musleabihf.tar.gz"
[[LLVMLibcxx]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fca9374fa581a41884afaa8f3c88f6f2962402a3"
libc = "musl"
os = "linux"

    [[LLVMLibcxx.download]]
    sha256 = "ea1bb88bf9c4e2f1c1e172fb90e96316ae16ee79d1b3284f6f0c258603059242"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.0/LLVMLibcxx-v17.0.0-armv7l-linux-musleabihf.tar.gz"
[[LLVMLibcxx]]
arch = "x86_64"
git-tree-sha1 = "29dc94f257e54dce468a443cb182de81770b2e5d"
os = "windows"

    [[LLVMLibcxx.download]]
    sha256 = "bba3f77e871628deef00241655bde2c83427b2057ca49e046c4d960c05d99731"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.0/LLVMLibcxx-v17.0.0-x86_64-w64-mingw32.tar.gz"
[[LLVMLibcxx]]
arch = "i686"
git-tree-sha1 = "068e9d8c328ed4ed81a318d95b9043256ac9a305"
os = "windows"

    [[LLVMLibcxx.download]]
    sha256 = "37152c52575440adebc98f922482588a6d96f7129f72bcee295e0a166fd99a04"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.0/LLVMLibcxx-v17.0.0-i686-w64-mingw32.tar.gz"
[[LLVMLibcxx]]
arch = "x86_64"
git-tree-sha1 = "6d8898bf729265c599bfb528d177ebd1944ad5da"
os = "macos"
os_version = "17"

    [[LLVMLibcxx.download]]
    sha256 = "fced491b1bc6c91c79e9f0cf37a8a7f6bf3cd32a56afefdf3d90289fba1abfc5"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.0/LLVMLibcxx-v17.0.0-x86_64-apple-darwin17.tar.gz"
[[LLVMLibcxx]]
arch = "aarch64"
git-tree-sha1 = "5a37d5a6ce0a66b478fa1eff88de0a330711e265"
os = "macos"
os_version = "20"

    [[LLVMLibcxx.download]]
    sha256 = "e7561e89e2d799482bd2194c5e2a22e5cefb35a509459367ca0522ab23e1cc8d"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.0/LLVMLibcxx-v17.0.0-aarch64-apple-darwin20.tar.gz"

[[LLVMLibcxx-build_log]]
arch = "x86_64"
git-tree-sha1 = "2648b77e49262748fccc99b827c44e5cc317e9b2"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibcxx-build_log.download]]
    sha256 = "c3fa10b2ea338deb4514ffaa3d545d069d59f66404bd820895213d5064d91483"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.0/LLVMLibcxx-build_log-v17.0.0-x86_64-linux-gnu.tar.gz"
[[LLVMLibcxx-build_log]]
arch = "i686"
git-tree-sha1 = "44d02dd7d13b0b52185d2f4990e4e32c55107edf"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibcxx-build_log.download]]
    sha256 = "644a52790c81abf70a92913925b311c5fa73d852139d70480bca6bb2d3c7ee6b"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.0/LLVMLibcxx-build_log-v17.0.0-i686-linux-gnu.tar.gz"
[[LLVMLibcxx-build_log]]
arch = "aarch64"
git-tree-sha1 = "bd63537a5437b0d0a9794c40179e46e7263e82d4"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibcxx-build_log.download]]
    sha256 = "dc1e41a61a30ca48ba246c50b37cd4037b1c76a56ed6f0a707b302c467715c02"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.0/LLVMLibcxx-build_log-v17.0.0-aarch64-linux-gnu.tar.gz"
[[LLVMLibcxx-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fcb4e11bda57d153001c50503d2f69499f4a4df4"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibcxx-build_log.download]]
    sha256 = "eb7a7a31b14fbc1a98f9659bb71dcb4f47a9cf1a9595dcf88023fa8d32da2520"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.0/LLVMLibcxx-build_log-v17.0.0-armv7l-linux-gnueabihf.tar.gz"
[[LLVMLibcxx-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "3e344f3d888c4dce5d56c6d3dc2c9bec1eecc5ed"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibcxx-build_log.download]]
    sha256 = "490c7f48009d29c6e99f2db162d0a01356252d2f7b4600d813c6fab4e168b320"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.0/LLVMLibcxx-build_log-v17.0.0-powerpc64le-linux-gnu.tar.gz"
[[LLVMLibcxx-build_log]]
arch = "x86_64"
git-tree-sha1 = "15b4d0aac79ba002da12efc5e28bf113c175dd61"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibcxx-build_log.download]]
    sha256 = "5c022d862bd0b85ce5f3e571f30207d6f5c1171643b30edaa15b074d3ca8b42f"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.0/LLVMLibcxx-build_log-v17.0.0-x86_64-linux-musl.tar.gz"
[[LLVMLibcxx-build_log]]
arch = "i686"
git-tree-sha1 = "109e3a396357c04faf14b38795d534bae26894f4"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibcxx-build_log.download]]
    sha256 = "0539feb7090a3e96b05c87ed4cc5ca2bb3c788cf5e9764081332a619bfd999a7"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.0/LLVMLibcxx-build_log-v17.0.0-i686-linux-musl.tar.gz"
[[LLVMLibcxx-build_log]]
arch = "aarch64"
git-tree-sha1 = "41298136342a37198bfed32f897145233233f936"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibcxx-build_log.download]]
    sha256 = "90fb0367581c9b828f840541e0b54ca5bb5383742b0906ae8908dca67aa46643"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.0/LLVMLibcxx-build_log-v17.0.0-aarch64-linux-musl.tar.gz"
[[LLVMLibcxx-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9a9aa262b8b96b80190035a6fb975ead9d742c54"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibcxx-build_log.download]]
    sha256 = "135b8de12aa6d538a616cb4a5c9cc6da98ad6f55071eaf1875d03ab3df4e2f71"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.0/LLVMLibcxx-build_log-v17.0.0-armv6l-linux-musleabihf.tar.gz"
[[LLVMLibcxx-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "503dc2f0ec28856d2df512bedf165bb7c0be43de"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibcxx-build_log.download]]
    sha256 = "7dbd0fad82298272dd6fab42951b1eb927c2eec7e4af353449cacc67723cd58f"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.0/LLVMLibcxx-build_log-v17.0.0-armv7l-linux-musleabihf.tar.gz"
[[LLVMLibcxx-build_log]]
arch = "x86_64"
git-tree-sha1 = "a5b17bf18d705af1b97dda57b974d7c04edab524"
lazy = true
os = "windows"

    [[LLVMLibcxx-build_log.download]]
    sha256 = "ec5f4c73d3fecb2983345d36b419d49159e3cd11ce15ced4b67cba63110fcddd"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.0/LLVMLibcxx-build_log-v17.0.0-x86_64-w64-mingw32.tar.gz"
[[LLVMLibcxx-build_log]]
arch = "i686"
git-tree-sha1 = "210022aa1b58395a7ceefa76c3fbbc42433ebb50"
lazy = true
os = "windows"

    [[LLVMLibcxx-build_log.download]]
    sha256 = "eafb33fe0b99671a40412477fd3a033bf90d6041e7ba5bee6502730b12923f8a"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.0/LLVMLibcxx-build_log-v17.0.0-i686-w64-mingw32.tar.gz"
[[LLVMLibcxx-build_log]]
arch = "x86_64"
git-tree-sha1 = "b14583ee83d9a30cba85a94b152cb137f72d438a"
lazy = true
os = "macos"
os_version = "17"

    [[LLVMLibcxx-build_log.download]]
    sha256 = "d5624f2f3969663ef980d29a3615b11c80e85c6963891c46153d85bfbcaad45d"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.0/LLVMLibcxx-build_log-v17.0.0-x86_64-apple-darwin17.tar.gz"
[[LLVMLibcxx-build_log]]
arch = "aarch64"
git-tree-sha1 = "3dd5f1394b72988266a1a72ddb1e027f12481d32"
lazy = true
os = "macos"
os_version = "20"

    [[LLVMLibcxx-build_log.download]]
    sha256 = "3df57c5867bb9787977efd9d755c719706e52b26ff9cccd65d4f65ac052c76e7"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.0/LLVMLibcxx-build_log-v17.0.0-aarch64-apple-darwin20.tar.gz"

[[LLVMLibcxx-extract_log]]
arch = "x86_64"
git-tree-sha1 = "999fdfba1554a873aca319455da78756fc967dac"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibcxx-extract_log.download]]
    sha256 = "c17996f8d2df9886f8944d0b4ecd0412309bab7d46fd76709eefa7ab3baf6fb8"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.0/LLVMLibcxx-extract_log-v17.0.0-x86_64-linux-gnu.tar.gz"
[[LLVMLibcxx-extract_log]]
arch = "i686"
git-tree-sha1 = "d253b3dd5219d9de2d49b0592d2771cc12c3ab02"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibcxx-extract_log.download]]
    sha256 = "56894add3700f4067a13749bbfc19347f9162acdaabe5f741a92860d60935c66"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.0/LLVMLibcxx-extract_log-v17.0.0-i686-linux-gnu.tar.gz"
[[LLVMLibcxx-extract_log]]
arch = "aarch64"
git-tree-sha1 = "8b21c7ca70093fdf4b18a4a3d061eb005277b3d3"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibcxx-extract_log.download]]
    sha256 = "de31779f25c67daf7e72da49749e0bba35c5d208a4ab8177dd5cf8f256778ff4"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.0/LLVMLibcxx-extract_log-v17.0.0-aarch64-linux-gnu.tar.gz"
[[LLVMLibcxx-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bb72b8e5d33d5cc37dc89a9d494d25077f1d5704"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibcxx-extract_log.download]]
    sha256 = "0b58efad2d260231d73122e1bc980b78b8309d396def9a1a57514b420825664b"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.0/LLVMLibcxx-extract_log-v17.0.0-armv7l-linux-gnueabihf.tar.gz"
[[LLVMLibcxx-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "be835758e60ddee54fca8bdb1b64a303bda8ab63"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibcxx-extract_log.download]]
    sha256 = "b2a7942ded64887cf7e9d9d8353bc7ba7298452028d49f071e3747c24c5ecd76"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.0/LLVMLibcxx-extract_log-v17.0.0-powerpc64le-linux-gnu.tar.gz"
[[LLVMLibcxx-extract_log]]
arch = "x86_64"
git-tree-sha1 = "80ee3f4df2445a3f923dd76b57aaaa7d032ca3ab"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibcxx-extract_log.download]]
    sha256 = "ee6ce0c66526dd80afab0137d9916ee7094c06702fc0c38ed8b37abf9da22ce4"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.0/LLVMLibcxx-extract_log-v17.0.0-x86_64-linux-musl.tar.gz"
[[LLVMLibcxx-extract_log]]
arch = "i686"
git-tree-sha1 = "f1fd6502a9065756b7e7006d94a4d18b8fdc7fe0"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibcxx-extract_log.download]]
    sha256 = "9a8f88a3176d932364782ce87db51fb5447907d1d51a44678530d79f5f7afd81"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.0/LLVMLibcxx-extract_log-v17.0.0-i686-linux-musl.tar.gz"
[[LLVMLibcxx-extract_log]]
arch = "aarch64"
git-tree-sha1 = "5aae37a2b518600534e7f99a3a2139b638d663c9"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibcxx-extract_log.download]]
    sha256 = "b7dfe7ebb4db8fb2c2c5697cc3676418ed8d13e51f0edf2094e6b6c9e7607f01"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.0/LLVMLibcxx-extract_log-v17.0.0-aarch64-linux-musl.tar.gz"
[[LLVMLibcxx-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7bea4cd2d711284868ce4f91926044d6c870aa1a"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibcxx-extract_log.download]]
    sha256 = "64a89a4a563c0d873cfbf337b8b823693505a16277edcb328abdba0b183e481d"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.0/LLVMLibcxx-extract_log-v17.0.0-armv6l-linux-musleabihf.tar.gz"
[[LLVMLibcxx-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "29b05ed4c06062fc0a5a8f1748672cc688572edf"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibcxx-extract_log.download]]
    sha256 = "f9805e50e0c4e41ad4568f1029eb9702575179f856de1296e045ddb7c360446d"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.0/LLVMLibcxx-extract_log-v17.0.0-armv7l-linux-musleabihf.tar.gz"
[[LLVMLibcxx-extract_log]]
arch = "x86_64"
git-tree-sha1 = "6ecdaf70439d04bbf8fce4f1520ed25592f696c2"
lazy = true
os = "windows"

    [[LLVMLibcxx-extract_log.download]]
    sha256 = "b822ce84992318b06c33b56d7f6063f6b3dfc63c110bcee6573b624491090274"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.0/LLVMLibcxx-extract_log-v17.0.0-x86_64-w64-mingw32.tar.gz"
[[LLVMLibcxx-extract_log]]
arch = "i686"
git-tree-sha1 = "a9b23300511e8e008c2b5d115b760c82ecd0f27d"
lazy = true
os = "windows"

    [[LLVMLibcxx-extract_log.download]]
    sha256 = "abd6bb8e65c2a064f8262fe15b82619bb72bdebced428f9fb3dfac8884574b9b"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.0/LLVMLibcxx-extract_log-v17.0.0-i686-w64-mingw32.tar.gz"
[[LLVMLibcxx-extract_log]]
arch = "x86_64"
git-tree-sha1 = "565480f790aa1a92c35d9f952f567c089a3f9f8c"
lazy = true
os = "macos"
os_version = "17"

    [[LLVMLibcxx-extract_log.download]]
    sha256 = "fe3fcbe88d34baeef7f3693e691cfe08612ff8e7e778eae13b3e9ce9b1cdcf78"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.0/LLVMLibcxx-extract_log-v17.0.0-x86_64-apple-darwin17.tar.gz"
[[LLVMLibcxx-extract_log]]
arch = "aarch64"
git-tree-sha1 = "42b8db18962b8a802a349810b477abb04a4d8aa1"
lazy = true
os = "macos"
os_version = "20"

    [[LLVMLibcxx-extract_log.download]]
    sha256 = "b5e17b2ceff743f19fe1099b0b635b5ae58ce9d7875cdc83c10ae5abacac28e0"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.0/LLVMLibcxx-extract_log-v17.0.0-aarch64-apple-darwin20.tar.gz"
