[[LLVMLibcxx]]
arch = "x86_64"
git-tree-sha1 = "f451d9833ac1a91a45f85cf1266ec11736e665c0"
libc = "glibc"
os = "linux"

    [[LLVMLibcxx.download]]
    sha256 = "857ec670b031968d08f953162bea357fbc46cc373470f7c52ac82a68bcafcec3"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.1-GCC/LLVMLibcxx-v17.0.1-x86_64-linux-gnu.tar.gz"
[[LLVMLibcxx]]
arch = "i686"
git-tree-sha1 = "e6890d71f895134fe6cb6e1b33bb5fd5a6ba9849"
libc = "glibc"
os = "linux"

    [[LLVMLibcxx.download]]
    sha256 = "aa8d9110ab5966c3d906ae9dc2d2ebe9600d61fdd05866a798c94796da89a65a"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.1-GCC/LLVMLibcxx-v17.0.1-i686-linux-gnu.tar.gz"
[[LLVMLibcxx]]
arch = "aarch64"
git-tree-sha1 = "02e31e56e6b2f02332851cb4e8e23e1d5558461c"
libc = "glibc"
os = "linux"

    [[LLVMLibcxx.download]]
    sha256 = "3083fcdd0375e75eb00fa28a4a104de252bbdb0bde6614fb1e5a9e95c5dbb987"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.1-GCC/LLVMLibcxx-v17.0.1-aarch64-linux-gnu.tar.gz"
[[LLVMLibcxx]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ebd31967bd3fc6f5a481c6c823b6a0c75b1b9f64"
libc = "glibc"
os = "linux"

    [[LLVMLibcxx.download]]
    sha256 = "134fe50a71fe5d4481fb11ada5e84dfe56d705cf45cb211c323ef3cf3af9adb2"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.1-GCC/LLVMLibcxx-v17.0.1-armv7l-linux-gnueabihf.tar.gz"
[[LLVMLibcxx]]
arch = "powerpc64le"
git-tree-sha1 = "70137a9c192febb2775c03a6cadff8d3751d3e87"
libc = "glibc"
os = "linux"

    [[LLVMLibcxx.download]]
    sha256 = "bcc4e6d290250944a1a0964cf4e77737e1d8e1f195fcf798bbc5c8ba025b8180"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.1-GCC/LLVMLibcxx-v17.0.1-powerpc64le-linux-gnu.tar.gz"
[[LLVMLibcxx]]
arch = "x86_64"
git-tree-sha1 = "402fe6a179d73742065b7c9208de39017c98a4fa"
libc = "musl"
os = "linux"

    [[LLVMLibcxx.download]]
    sha256 = "1013a5b541b30156048fc4512d0f060794df27a8d84baf66c41507c9c31ac87b"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.1-GCC/LLVMLibcxx-v17.0.1-x86_64-linux-musl.tar.gz"
[[LLVMLibcxx]]
arch = "i686"
git-tree-sha1 = "dde94a9902009e7e8a2cc26a60ad3a9422695ff8"
libc = "musl"
os = "linux"

    [[LLVMLibcxx.download]]
    sha256 = "11c47f78be4949ff3281d3387556aefa86044d54461afefab60346e58f2ffbfa"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.1-GCC/LLVMLibcxx-v17.0.1-i686-linux-musl.tar.gz"
[[LLVMLibcxx]]
arch = "aarch64"
git-tree-sha1 = "4cc327dd48b96ee1e897531aa5ba20624395384f"
libc = "musl"
os = "linux"

    [[LLVMLibcxx.download]]
    sha256 = "407ae27c8b1693b7704a0308d178f1c3765d5d231bee000ce37b46692c90f898"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.1-GCC/LLVMLibcxx-v17.0.1-aarch64-linux-musl.tar.gz"
[[LLVMLibcxx]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "90b41819d91168aeb882c7754128e3d636934896"
libc = "musl"
os = "linux"

    [[LLVMLibcxx.download]]
    sha256 = "f60aa1e5b1c19eab9e6305874955f6553b6096d7d641231edf3ed1e6a415a451"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.1-GCC/LLVMLibcxx-v17.0.1-armv6l-linux-musleabihf.tar.gz"
[[LLVMLibcxx]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5c12b1d29cb58e37d338452473dbf6b77d46145a"
libc = "musl"
os = "linux"

    [[LLVMLibcxx.download]]
    sha256 = "6fc707c53f480f4f25fe53e4fa94f7fb6b5a944b45c7b75d927220cd057be395"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.1-GCC/LLVMLibcxx-v17.0.1-armv7l-linux-musleabihf.tar.gz"
[[LLVMLibcxx]]
arch = "x86_64"
git-tree-sha1 = "3fbec08fb881a6c214ff1796a9a764dfe3b58541"
os = "windows"

    [[LLVMLibcxx.download]]
    sha256 = "62f809a48d353fc8d8dfa41f420f75a13a951f565f736dbdeaac792de3aef5fc"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.1-GCC/LLVMLibcxx-v17.0.1-x86_64-w64-mingw32.tar.gz"
[[LLVMLibcxx]]
arch = "i686"
git-tree-sha1 = "647cdc220c8ce3d6538c0b73c3bafee31ee800cf"
os = "windows"

    [[LLVMLibcxx.download]]
    sha256 = "5daf0791df86997f9f7d301817ac89672b32b449014c4034235aa36f972261f1"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.1-GCC/LLVMLibcxx-v17.0.1-i686-w64-mingw32.tar.gz"

[[LLVMLibcxx-build_log]]
arch = "x86_64"
git-tree-sha1 = "0a2acfe55f2c8cd3c138f23ccca41c44b42ad938"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibcxx-build_log.download]]
    sha256 = "0181768393f1a485a241e05ad9b97d87a897bc7027b1a6f5fb56953ae9535da3"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.1-GCC/LLVMLibcxx-build_log-v17.0.1-x86_64-linux-gnu.tar.gz"
[[LLVMLibcxx-build_log]]
arch = "i686"
git-tree-sha1 = "47e6cce6c8380976f038052aacdc0a8687a54641"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibcxx-build_log.download]]
    sha256 = "473708d56c37b597b9b63f8e74201cd6d141e0e7ff477c755b928d6b1746b29e"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.1-GCC/LLVMLibcxx-build_log-v17.0.1-i686-linux-gnu.tar.gz"
[[LLVMLibcxx-build_log]]
arch = "aarch64"
git-tree-sha1 = "33d342263251a0135ca6037af891a85f7a882502"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibcxx-build_log.download]]
    sha256 = "8cdc61dbc829b122bebe58c72a8762a320843f3a4d96322adb7abef2b18a0360"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.1-GCC/LLVMLibcxx-build_log-v17.0.1-aarch64-linux-gnu.tar.gz"
[[LLVMLibcxx-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a86f61e4b395b5f0db939894f36ab9202c5d708e"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibcxx-build_log.download]]
    sha256 = "4016797de27a5bdb3a06ce9e6bb510ba2b388f0d3e57a31063f052165d58246a"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.1-GCC/LLVMLibcxx-build_log-v17.0.1-armv7l-linux-gnueabihf.tar.gz"
[[LLVMLibcxx-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "4dcd28fdf457dfe67d369ba8cbde7664a2b0fd93"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibcxx-build_log.download]]
    sha256 = "b1569d970d330df086ff4f8c0cb144cbd6712b1fa225806ba356e74cf568e3d1"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.1-GCC/LLVMLibcxx-build_log-v17.0.1-powerpc64le-linux-gnu.tar.gz"
[[LLVMLibcxx-build_log]]
arch = "x86_64"
git-tree-sha1 = "bc3cb1e177682d62da86e4c34a6e01c07740818f"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibcxx-build_log.download]]
    sha256 = "4e41a55b296d1aa01a41489f73703b8c1554f8f5dfab70a48ff2804f8fa3af53"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.1-GCC/LLVMLibcxx-build_log-v17.0.1-x86_64-linux-musl.tar.gz"
[[LLVMLibcxx-build_log]]
arch = "i686"
git-tree-sha1 = "caa5f6d8642b2e63eb05fa845d97750244c6695d"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibcxx-build_log.download]]
    sha256 = "ec8861a8489b069f0f41c789468e096dbb516903fb014f128ae333c4578a0e49"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.1-GCC/LLVMLibcxx-build_log-v17.0.1-i686-linux-musl.tar.gz"
[[LLVMLibcxx-build_log]]
arch = "aarch64"
git-tree-sha1 = "5a2597f46b85f12bfa87bd4c46e8e01a1bad6105"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibcxx-build_log.download]]
    sha256 = "361a766a4ac122dc00057426f9ff9149093dd026e58be5eb9908d5a629e3be20"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.1-GCC/LLVMLibcxx-build_log-v17.0.1-aarch64-linux-musl.tar.gz"
[[LLVMLibcxx-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "704b8322f81ae9e61ed5a0152c7c7cba57f30e2b"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibcxx-build_log.download]]
    sha256 = "8362a2979f3852e01d80fc1079d050c0229b453594739a9e90d1f916bd3d394f"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.1-GCC/LLVMLibcxx-build_log-v17.0.1-armv6l-linux-musleabihf.tar.gz"
[[LLVMLibcxx-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e548b8db17bd02eb985382a35104dda2c3339509"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibcxx-build_log.download]]
    sha256 = "e24e4ca884073938cc8efd8846a7fe01a0b6de7181adfd452641f1e9482a4c5d"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.1-GCC/LLVMLibcxx-build_log-v17.0.1-armv7l-linux-musleabihf.tar.gz"
[[LLVMLibcxx-build_log]]
arch = "x86_64"
git-tree-sha1 = "9e5308edda12f1bd1312124eacb95edc87ee6286"
lazy = true
os = "windows"

    [[LLVMLibcxx-build_log.download]]
    sha256 = "0f4cd49414db3db2a297f615f8299d2d667d9bc7c11aae2651264daa41314604"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.1-GCC/LLVMLibcxx-build_log-v17.0.1-x86_64-w64-mingw32.tar.gz"
[[LLVMLibcxx-build_log]]
arch = "i686"
git-tree-sha1 = "f59fe910c30de72bdd7a8b3027c6c6211feba31b"
lazy = true
os = "windows"

    [[LLVMLibcxx-build_log.download]]
    sha256 = "fab413bab486abb960eff314141aed5a8d659e609dbd04759e615f4ea99742b0"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.1-GCC/LLVMLibcxx-build_log-v17.0.1-i686-w64-mingw32.tar.gz"

[[LLVMLibcxx-extract_log]]
arch = "x86_64"
git-tree-sha1 = "aada1691428f9ed5b432f6de9a03a9e0df24082c"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibcxx-extract_log.download]]
    sha256 = "7735db26c55794b6610c717eeddc9dec5565590c8ea8b2958af5757e529b5e35"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.1-GCC/LLVMLibcxx-extract_log-v17.0.1-x86_64-linux-gnu.tar.gz"
[[LLVMLibcxx-extract_log]]
arch = "i686"
git-tree-sha1 = "3e96d9ee02322d6bf7059fbb545ba22e76d8a49e"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibcxx-extract_log.download]]
    sha256 = "aac7037d9f246c7645369356846b92869de4c4930014db68f83bf0cc1f717732"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.1-GCC/LLVMLibcxx-extract_log-v17.0.1-i686-linux-gnu.tar.gz"
[[LLVMLibcxx-extract_log]]
arch = "aarch64"
git-tree-sha1 = "476c1d3dc8a638e6924918509566272cc642a7ca"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibcxx-extract_log.download]]
    sha256 = "3d3afafdbba12d8d268b97eb214f619c0c4e8a7bf29f1a6ad3d62994fdcfd073"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.1-GCC/LLVMLibcxx-extract_log-v17.0.1-aarch64-linux-gnu.tar.gz"
[[LLVMLibcxx-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0b12803e46d7d73c95285a3bf9ff58a48dcbb5d8"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibcxx-extract_log.download]]
    sha256 = "5647b0d52b81e89d0b7ac554115b656c317760949b7e4bfbd451149def95f19c"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.1-GCC/LLVMLibcxx-extract_log-v17.0.1-armv7l-linux-gnueabihf.tar.gz"
[[LLVMLibcxx-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "3bb4b81316378c1527925104f40aeadc675e3898"
lazy = true
libc = "glibc"
os = "linux"

    [[LLVMLibcxx-extract_log.download]]
    sha256 = "75f32e4b497a013484e76b27be25e81799e4d74668d78a1aa16316568ea8394a"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.1-GCC/LLVMLibcxx-extract_log-v17.0.1-powerpc64le-linux-gnu.tar.gz"
[[LLVMLibcxx-extract_log]]
arch = "x86_64"
git-tree-sha1 = "552ad4da32bab8daf6698c7fc830cd9249c5f019"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibcxx-extract_log.download]]
    sha256 = "d941b64fd4c3b533f5d1bdbfd5102abc151c8770ebca57f5c7c4cbe3348768bf"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.1-GCC/LLVMLibcxx-extract_log-v17.0.1-x86_64-linux-musl.tar.gz"
[[LLVMLibcxx-extract_log]]
arch = "i686"
git-tree-sha1 = "24579c1149274f6925b2adb6e14475a0c54d89c3"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibcxx-extract_log.download]]
    sha256 = "31614e1fcc7e0552d1ba6ab7e7dee1ad3282f6ffdc51e4eb0349843fd8535625"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.1-GCC/LLVMLibcxx-extract_log-v17.0.1-i686-linux-musl.tar.gz"
[[LLVMLibcxx-extract_log]]
arch = "aarch64"
git-tree-sha1 = "aa217a21744968b8ab1f7592374ce193c2bb862f"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibcxx-extract_log.download]]
    sha256 = "56ce9c54e4310df0d9d43d3b15fcb4b887d6ce4f4a9764de8d6ee6fa7647aeb2"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.1-GCC/LLVMLibcxx-extract_log-v17.0.1-aarch64-linux-musl.tar.gz"
[[LLVMLibcxx-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cc5e59c338bd6648930cd41f95b0fbd31e81a382"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibcxx-extract_log.download]]
    sha256 = "56e2ab8eb30107ab2a7c582a9a61b63cde0aa67a152e1d351497a23a5c08ab10"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.1-GCC/LLVMLibcxx-extract_log-v17.0.1-armv6l-linux-musleabihf.tar.gz"
[[LLVMLibcxx-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d76c30617d5f27b7c229c448bf08f89b6dd22b50"
lazy = true
libc = "musl"
os = "linux"

    [[LLVMLibcxx-extract_log.download]]
    sha256 = "6e74191c0dbd44c8d09847ec67489535be9f243cdd324995aeb9a3109bf6c78b"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.1-GCC/LLVMLibcxx-extract_log-v17.0.1-armv7l-linux-musleabihf.tar.gz"
[[LLVMLibcxx-extract_log]]
arch = "x86_64"
git-tree-sha1 = "2e3056da6ee58d9ea6f01904c872c62ebd17ec87"
lazy = true
os = "windows"

    [[LLVMLibcxx-extract_log.download]]
    sha256 = "c7a5a20ce709ed01e0ce4ddf275c5b15d21073a5a67cfc90917cfaa7f5b6a62e"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.1-GCC/LLVMLibcxx-extract_log-v17.0.1-x86_64-w64-mingw32.tar.gz"
[[LLVMLibcxx-extract_log]]
arch = "i686"
git-tree-sha1 = "9e659c91dd3c0d30c38e32f0106fc66a6e402703"
lazy = true
os = "windows"

    [[LLVMLibcxx-extract_log.download]]
    sha256 = "0f8c993ef81ce2b4df62f47dd7ba4eef2378fa2da90c01c3cac440290892e763"
    url = "https://github.com/staticfloat/LLVMLibcxx_jll.jl/releases/download/v17.0.1-GCC/LLVMLibcxx-extract_log-v17.0.1-i686-w64-mingw32.tar.gz"
